name: ayol_uchun
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  go_router: ^14.6.3
  provider: ^6.1.2
  dio: ^5.7.0
  cached_network_image: ^3.4.1
  flutter_secure_storage:
    git:
      url: https://github.com/mogol/flutter_secure_storage.git
      ref: master
      path: flutter_secure_storage

  image_picker: ^1.1.2
  flutter_localizations:
    sdk: flutter
  video_player: ^2.9.3
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^9.1.0
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  equatable: ^2.0.7
  intl: ^0.20.2
  build_runner: ^2.4.15
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  bloc: ^9.0.0
  google_sign_in: ^6.3.0
  pinput: ^5.0.1
  url_launcher: ^6.3.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.5



  flutter_lints: ^5.0.0

flutter:
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/open-sans/OpenSans-Light.ttf
          weight: 300
        - asset: fonts/open-sans/OpenSans-Regular.ttf
          weight: 400
        - asset: fonts/open-sans/OpenSans-SemiBold.ttf
          weight: 600
        - asset: fonts/open-sans/OpenSans-Bold.ttf
          weight: 700
        - asset: fonts/open-sans/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/open-sans/OpenSans-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/open-sans/OpenSans-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/open-sans/OpenSans-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: fonts/open-sans/OpenSans-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: fonts/open-sans/OpenSans-ExtraBoldItalic.ttf
          style: italic
          weight: 800


    # The following line ensures that the Material Icons font is


  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

